// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAehLbNfR8Tl32p_9kfMVi2q94ZF3fDb5c',
    appId: '1:190651460115:web:c003bbc2303efdd466ede6',
    messagingSenderId: '190651460115',
    projectId: 'flutterapp-8236e',
    authDomain: 'flutterapp-8236e.firebaseapp.com',
    storageBucket: 'flutterapp-8236e.appspot.com',
    measurementId: 'G-H56D51MSXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC02jpBPLcnuItXaeWPCtqYBc9aVphISzE',
    appId: '1:190651460115:android:8aa9d225b92dfa4566ede6',
    messagingSenderId: '190651460115',
    projectId: 'flutterapp-8236e',
    storageBucket: 'flutterapp-8236e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPT67GkXN9OO1U8EK9yGkA-AQYRXgOAAI',
    appId: '1:190651460115:ios:520cf3a486e5ab7566ede6',
    messagingSenderId: '190651460115',
    projectId: 'flutterapp-8236e',
    storageBucket: 'flutterapp-8236e.appspot.com',
    iosClientId: '190651460115-0vhelu6do8sammvh6f5qfsgrgh5hgn7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPT67GkXN9OO1U8EK9yGkA-AQYRXgOAAI',
    appId: '1:190651460115:ios:520cf3a486e5ab7566ede6',
    messagingSenderId: '190651460115',
    projectId: 'flutterapp-8236e',
    storageBucket: 'flutterapp-8236e.appspot.com',
    iosClientId: '190651460115-0vhelu6do8sammvh6f5qfsgrgh5hgn7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
